; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

;[env:nano33ble]
;platform = nordicnrf52
;board = nano33ble
;framework = arduino

[env:nano33ble_sense]
platform = nordicnrf52
board = nano33ble
framework = arduino

monitor_speed = 115200
build_flags =
    -DARDUINO_NANO33BLE_SENSE

; tego nie ma    arduino-libraries/Arduino_LSM9DS1
; fix - Nowy sensor to LSM6DSOX (IMU) + LIS3MDL (magnetometr).
; fix wszystkie sensory w core
; lib_deps =
;     arduino-libraries/Arduino_LSM6DSOX
;     arduino-libraries/Arduino_HS3003
;     arduino-libraries/Arduino_LPS22DF
;     arduino-libraries/Arduino_APDS9960
;     arduino-libraries/ArduinoBLE

lib_deps =
    arduino-libraries/Arduino_APDS9960
    arduino-libraries/ArduinoBLE
;    arduino-libraries/Arduino_LSM6DSOX
; bootland
    arduino-libraries/Arduino_BMI270_BMM150
